name: stress_pilot
description: "Load testing software"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider:
  get_it:
  injectable:

  # UI Components
  google_fonts:

  # HTTP
  dio:
  dio_cookie_manager:
  cookie_jar:
  web_socket_channel:

  # File Handling
  file_picker:
  path_provider:
  path:

  # Utilities
  uuid:

  # Storage
  shared_preferences:

  # Process Management
  http_parser: ^4.1.2
  stomp_dart_client: ^3.0.1
  fl_chart: ^1.1.1
  window_manager: ^0.5.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2
  puppeteer: ^3.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  inno_bundle: ^0.11.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/core/
    - assets/fonts/

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/images/logo.png"

  windows:
    generate: true
    icon_size: 256

  linux:
    generate: true

inno_bundle:
  id: a8bea9a0-e96d-11f0-85ae-7f61cad0019a
  publisher: Ly Hien Long
  name: Stress Pilot